export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_FOR_UPDATE = "GET_PRODUCT_FOR_UPDATE";
export const CLEAR_UPDATING_PRODUCT = "CLEAR_UPDATING_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const OPEN_UPDATE_FORM = "OPEN_UPDATE_FORM";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_PRODUCT_SUBMIT = "UPDATE_PRODUCT_SUBMIT";
export const OPEN_CART = "OPEN_CART";
export const AUTHENTICATED = "AUTHENTICATED";
export const LOGOUT ="LOGOUT";



